apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: strategies
data:
  strategies.s: |
    module kubow.strategies;
    import model "KubeZnnSystem:Acme" { KubeZnnSystem as M, KubernetesFam as K };
    import lib "tactics.s";
    import op "org.sa.rainbow.model.stitch.*";

    define boolean cHiRespTime = M.kubeZnnS.latency > M.MAX_RESPTIME;
    define boolean cLoRespTime = M.kubeZnnS.latency < M.MAX_RESPTIME;
    define boolean canAddPod = M.kubeZnnD.maxReplicas > M.kubeZnnD.desiredReplicas;
    define boolean canRemovePod = M.kubeZnnD.minReplicas < M.kubeZnnD.desiredReplicas;

    strategy ReduceRespTime [ cHiRespTime ] {
      t0: (cHiRespTime && canAddPod) -> addReplicas(1) @[30000 /*ms*/] {
        t0a: (success) -> done;
      }
      t1: (default) -> TNULL;
    }

    strategy ReduceCost [ cLoRespTime ] {
      t0: (cLoRespTime && canRemovePod) -> removeReplicas(1) @[30000 /*ms*/] {
        t0a: (success) -> done;
      }
      t1: (default) -> TNULL;
    }