---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
spec:
  type: LoadBalancer
#  externalIPs:
#    - 132.145.192.179   
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31191      
      protocol: TCP
  selector:
    app: grafana
