apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: ingress-nginx
    http:
      paths:
      - path: /znn(/|$)(.*)
        backend:
          serviceName: kube-znn
          servicePort:  8080