apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: gauges
data:
  gauges.yaml: |
    gauge-types:
      KubowGaugeT:
        commands:
          setServiceProperty: ServiceT.setServiceProperty (Object)
          setDeploymentInfo: DeploymentT.setDeploymentInfo (Object)
          setDeploymentProperty: DeploymentT.setDeploymentProperty (Object)
        setupParams:
          targetIP:
            type: String
            default: "127.0.0.1"
          propertyPath:
            type: String
            default: ""
          propertyName:
            type: String
            default: ""
          beaconPeriod:
            type: long
            default: 3000
          javaClass:
            type: String
            default: "br.unifor.kubow.gauges.KubowGauge"
        configParams:
          targetProbeType:
            type: String
            default: ~
        comment: ""
    gauge-instances:
      GLatency:
        type: KubowGaugeT
        model: "KubeZnnSystem:Acme"
        commands:
          "setServiceProperty()": "kubeZnnS.setServiceProperty($<jsonValue>,<latency>)"
        setupValues:
          targetIP: "127.0.0.1"
        configValues:
          targetProbeType: default-kube-znn-latency@*
          

      GDeploymentInfo:
        type: KubowGaugeT
        model: "KubeZnnSystem:Acme"
        commands:
          "setDeploymentInfo()": kubeZnnD.setDeploymentInfo($<jsonValue>)
        setupValues:
          targetIP: "127.0.0.1"
        configValues:
          targetProbeType: deployments.default.kube-znn.probe@*