apiVersion: v1
kind: ConfigMap
metadata:
  name: scripts-cm
data:
  locustfile.py: |
    from locust import HttpLocust, TaskSet
    import random

    def htppcall(l):                
        l.client.get("/news.php")

    class UserBehavior(TaskSet):
        tasks = {htppcall: 1}

    class WebsiteUser(HttpLocust):
        task_set = UserBehavior
