---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-server
  namespace: kube-system
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: metrics-server
  namespace: kube-system
  labels:
    app: metrics-server
    version: v1
spec:
  selector:
    matchLabels:
      app: metrics-server
      version: v1
  template:
    metadata:
      name: metrics-server
      labels:
        app: metrics-server
        version: v1
    spec:
      nodeSelector:
        kops.k8s.io/instancegroup: 'monitoring'       
      serviceAccountName: metrics-server
      volumes:
      # mount in tmp so we can safely use from-scratch images and/or read-only containers
      - name: tmp-dir
        emptyDir: {}
      containers:
      - command:
        - /metrics-server
        - --kubelet-insecure-tls
        - --kubelet-preferred-address-types=InternalIP
        name: metrics-server
        image: k8s.gcr.io/metrics-server-amd64:v0.3.1
        ports:
        - containerPort: 443
        imagePullPolicy: Always
        volumeMounts:
        - name: tmp-dir
          mountPath: /tmp