apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: kube-znn-autoscaling
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kube-znn
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Pods
    pods:
      metricName: nginx_ingress_controller_request_duration_seconds_success_99p
      targetAverageValue: 2000m  

# apiVersion: autoscaling/v2beta1
# kind: HorizontalPodAutoscaler
# metadata:
#   name: kube-znn
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: kube-znn
#   minReplicas: 2
#   maxReplicas: 10
#   metrics:
#   - type: Object
#     object: 
#       metricName: nginx_ingress_controller_request_duration_seconds_success_99p
#       target: 
#         apiVersion: v1
#         kind: Service
#         name: ingress-nginx
#       targetValue: 1      

# apiVersion: autoscaling/v2beta1
# kind: HorizontalPodAutoscaler
# metadata:
#   name: kube-znn-autoscaling
#   namespace: default
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: kube-znn
#   minReplicas: 1
#   maxReplicas: 5
#   metrics:
#   - type: Pods
#     pods:
#       metricName: nginx_ingress_controller_request_duration_seconds_rate_99_pct
#       targetAverageValue: 2000m     
                          
# apiVersion: autoscaling/v2beta2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: kube-znn
#   namespace: default
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: kube-znn
#   minReplicas: 1
#   maxReplicas: 10
#   metrics:
#   - type: Pods
#     pods:
#       metric:
#         name: nginx_ingress_controller_request_duration_seconds_success_99p
#       target:
#         type: AverageValue
#         averageValue: 20k
#   - type: Object
#     object:
#       metric:
#         name: nginx_ingress_controller_request_duration_seconds_success_99p
#       describedObject:
#         apiVersion: networking.k8s.io/v1beta1
#         kind: Service
#         name: kube-znn
#       target:
#         type: Value
#         value: 10k

# apiVersion: autoscaling/v2beta1
# kind: HorizontalPodAutoscaler
# metadata:
#   name: kube-znn-autoscaling
#   namespace: default
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: kube-znn
#   minReplicas: 1
#   maxReplicas: 5
#   metrics:
#   - type: Object
#     object:
#       target:
#         kind: Service
#         name: kube-znn
#       metricName: nginx_ingress_controller_request_duration_seconds_sum
#       targetValue: 2000m       
  # - type: Pods
  #   pods:
  #     metricName: nginx_ingress_controller_request_duration_seconds_success_99p
  #     targetAverageValue: 2000m     
                          
# apiVersion: autoscaling/v2beta2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: kube-znn-autoscaling
#   namespace: default
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: kube-znn
#   minReplicas: 1
#   maxReplicas: 5
#   metrics:
#   - type: Object
#     object:
#       metric:
#         name: requests-per-second
#       describedObject:
#         apiVersion: extensions/v1beta1
#         kind: Ingress
#         name: ingress
#       target:
#         type: Value
#         value: 2000m  
  # - type: Pods
  #   pods:
  #     metric:
  #       name: envoy_cluster_external_upstream_rq_time_success_99p
  #     describedObject:
  #       apiVersion: v1
  #       kind: Pods
  #       name: ambassador
  #     target:
  #       type: Value
  #       value: 2000m

        
  # - type: Object
  #   object:
  #     target:
  #       kind: Deployment
  #       name: ambassador
  #     metricName: envoy_cluster_external_upstream_rq_time_success_99p
  #     targetValue: 2000m     

  # - type: Pods
  #   pods:
  #     metricName: envoy_cluster_external_upstream_rq_time_success_99p
  #     targetAverageValue: 2000m     

# apiVersion: autoscaling/v2beta2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: kube-znn-autoscaling
#   namespace: default
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: kube-znn
#   minReplicas: 1
#   maxReplicas: 10
#   metrics:
#   - type: Object
#     object:
#       metric:
#         name: requests-per-second
#       describedObject:
#         apiVersion: extensions/v1beta1
#         kind: Ingress
#         name: ingress
#       target:
#         type: Value
#         value: 2000m

# apiVersion: autoscaling/v2beta1
# kind: HorizontalPodAutoscaler
# metadata:
#   name: kube-znn-autoscaling
#   namespace: default
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: kube-znn
#   minReplicas: 1
#   maxReplicas: 5
#   metrics:
#   - type: Pods
#     pods:
#       metricName: nginx_ingress_controller_request_duration_success_99p
#       targetAverageValue: 2000m     
                                                                              
# apiVersion: autoscaling/v2beta1
# kind: HorizontalPodAutoscaler
# metadata:
#   name: kube-znn-autoscaler
#   namespace: default
# spec:
#   scaleTargetRef:
#     apiVersion: extensions/v1beta1
#     kind: Deployment
#     name: kube-znn
#   minReplicas: 1
#   maxReplicas: 10
#   metrics:
#   - type: Object
#     object:
#       target:
#         kind: Service
#         name: ingress
#       metricName: nginx_ingress_controller_request_duration_seconds_sum
#       targetValue: 2000m     
