version: '3'
services:
  grafana:
    container_name: grafana
    image: grafana/grafana
    environment:
      GF_SERVER_ROOT_URL: http://localhost
      GF_SECURITY_ADMIN_PASSWORD: master
    ports:
      - 3000:3000
